name: Docker Image CI for backend

on:
  push:
    branches: [ master ]
    paths: [ backend/** ]

jobs:

  build:

    runs-on: ubuntu-latest
    

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    
    - uses: actions/checkout@v3
    - name: Build the Docker image for backend
      run: |
        cd backend/api_server/
        docker build --tag ghcr.io/intothefantasy/api_backend:latest .
        docker push ghcr.io/intothefantasy/api_backend:latest
        
      
    
   
